# Generated by Django 6.0.3 on 2026-03-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_record_created_at_record_updated_at_tag_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inteligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('instructions', models.TextField()),
            ],
        ),
    ]
